const datas = {
    privilege:[
        {
            logo:require('@/assets/images/home/privilege1.png'),
            title:'0元购',
            subTitle:'1000+好货',
            label:false,
        },
        {
            logo:require('@/assets/images/home/privilege2.png'),
            title:'新人红包',
            subTitle:'最高可送50元!',
            label:false,
        },
        {
            logo:require('@/assets/images/home/privilege3.png'),
            title:'购物返利',
            subTitle:'购物还可拿钱!',
            label:false,
        },
        {
            logo:require('@/assets/images/home/privilege4.png'),
            title:'加油优惠',
            subTitle:'9折起优惠',
            label:true,
        },
        {
            logo:require('@/assets/images/home/privilege5.png'),
            title:'全球大牌',
            subTitle:'精选顶级奢侈品',
            label:false,
        },
        {
            logo:require('@/assets/images/home/privilege6.png'),
            title:'吃喝玩乐',
            subTitle:'星巴克永久折',
            label:false,
        },
    ],
    privilege8:[
        {
            logo:require('@/assets/images/home/privilege5.png'),
            title:'全球好物',
            subTitle:'0元领取',
            outLet:'每单省99%',
            label:false,
        },
        {
            logo:require('@/assets/images/home/privilege2.png'),
            title:'麒麟会员',
            subTitle:'尊享红包 ',
            outLet:'最高50元!!',
            label:false,
        },
        {
            logo:require('@/assets/images/home/privilege3.png'),
            title:'购物返利',
            subTitle:'买的多返得多',
            outLet:'超多优惠等你拿',
            label:false,
        },
    ],
    discount:[
        {
            logo:require('@/assets/images/home/discount1.png'),
            title:'话费立减券',
            subTitle:'移动电信联通',
            label:true,
        },
        {
            logo:require('@/assets/images/home/discount2.png'),
            title:'优酷会员',
            subTitle:'会员4折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount3.png'),
            title:'爱奇艺会员',
            subTitle:'会员5折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount4.png'),
            title:'腾讯会员',
            subTitle:'会员5折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount5.png'),
            title:'QQ音乐会员',
            subTitle:'会员4折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount6.png'),
            title:'外卖立减',
            subTitle:'红包天天领',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount7.png'),
            title:'肯德基',
            subTitle:'会员6折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount8.png'),
            title:'必胜客',
            subTitle:'尊享5折起',
            label:false,
        },
    ],
    discount2:[
        {
            logo:require('@/assets/images/home/discount1.png'),
            title:'话费立减券',
            subTitle:'移动电信联通',
            label:true,
        },
        {
            logo:require('@/assets/images/home/discount2.png'),
            title:'优酷会员',
            subTitle:'会员4折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount3.png'),
            title:'爱奇艺会员',
            subTitle:'会员5折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount7.png'),
            title:'肯德基',
            subTitle:'会员6折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount8.png'),
            title:'必胜客',
            subTitle:'尊享5折起',
            label:false,
        },
    ],
    discount6:[
        {
            logo:require('@/assets/images/home/discount1.png'),
            title:'话费立减券',
            subTitle:'移动电信联通',
            label:true,
        },
        {
            logo:require('@/assets/images/home/discount3.png'),
            title:'爱奇艺会员',
            subTitle:'会员5折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount6.png'),
            title:'外卖立减',
            subTitle:'红包天天领',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount7.png'),
            title:'肯德基',
            subTitle:'会员6折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount8.png'),
            title:'必胜客',
            subTitle:'尊享5折起',
            label:false,
        },
    ],
    discount8:[
        {
            logo:require('@/assets/images/home/discountNew1.png'),
            title:'全国280城',
            subTitle:'加油特惠',
            outLet:'每升最高省1.8元',
            label:true,
        },
        {
            logo:require('@/assets/images/home/discountNew2.png'),
            title:'热门视频',
            subTitle:'会员充值 ',
            outLet:'7折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discountNew3.png'),
            title:'电影票',
            subTitle:'超级优惠',
            outLet:'7折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discountNew4.png'),
            title:'外卖红包',
            subTitle:'天天领',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discountNew5.png'),
            title:'星巴克',
            subTitle:'咖啡24元起 ',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discountNew6.png'),
            title:'线上超市',
            subTitle:'买单8.8折 ',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discountNew7.png'),
            title:'尊享',
            subTitle:'免费洗车 ',
            label:true,
        },
        {
            logo:require('@/assets/images/home/discountNew8.png'),
            title:'更多会员 ',
            subTitle:'特权 ',
            label:false,
        },
    ],
    globalBrand:{
        BRISTION:[
            {
                logo:require('@/assets/images/home/globalBrand/BRISTION1.png'),
            },
            {
                logo:require('@/assets/images/home/globalBrand/BRISTION2.png'),
            },
            {
                logo:require('@/assets/images/home/globalBrand/BRISTION3.png'),
            },
        ],
        ELLE:[
            {
                logo:require('@/assets/images/home/globalBrand/ELLE1.png'),
            },
            {
                logo:require('@/assets/images/home/globalBrand/ELLE2.png'),
            },
            {
                logo:require('@/assets/images/home/globalBrand/ELLE3.png'),
            },
            {
                logo:require('@/assets/images/home/globalBrand/ELLE3.png'),
            },
        ],
        mula:[
            {
                logo:require('@/assets/images/home/globalBrand/mula1.png'),
            },
            {
                logo:require('@/assets/images/home/globalBrand/mula2.png'),
            },
            {
                logo:require('@/assets/images/home/globalBrand/mula3.png'),
            },
            {
                logo:require('@/assets/images/home/globalBrand/mula4.png'),
            },
        ]
            
    },
    globalBrand8:{
        JX:require('@/assets/images/home/globalBrandJX.png'),
        MZ:require('@/assets/images/home/globalBrandMZ.png'),
        MS:require('@/assets/images/home/globalBrandMS.png'),
        NZ:require('@/assets/images/home/globalBrandNZ.png'),
    },
    seckillImgList:{
        time10:require('@/assets/images/home/seckill1.png'),
        time12:require('@/assets/images/home/seckill2.png'),
        time16:require('@/assets/images/home/seckill3.png'),
        time20:require('@/assets/images/home/seckill4.png'),
        time22:require('@/assets/images/home/seckill5.png'),
    },
    membershipPrivileges:{
        hotRecommend:[
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend1.png'),
                title:'腾讯会员',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend2.png'),
                title:'爱奇艺会员',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend3.png'),
                title:'美团外卖',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend4.png'),
                title:'优酷会员',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend5.png'),
                title:'肯德基',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend6.png'),
                title:'芒果TV',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend7.png'),
                title:'星巴克',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend8.png'),
                title:'国际驾照',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend9.png'),
                title:'大众点评',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend10.png'),
                title:'饿了么会员',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend11.png'),
                title:'猫眼电影',
                subTitle:'低至8.5折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend12.png'),
                title:'QQ会员',
                subTitle:'会员7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend13.png'),
                title:'淘票票代金券',
                subTitle:'低至4折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend14.png'),
                title:'话费充值',
                subTitle:'优惠快捷',
            },
        ],
        hotRecommend2:[
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend2.png'),
                title:'爱奇艺会员',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend4.png'),
                title:'优酷会员',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend5.png'),
                title:'肯德基',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend6.png'),
                title:'芒果TV',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend7.png'),
                title:'星巴克',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend8.png'),
                title:'国际驾照',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend10.png'),
                title:'饿了么会员',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend11.png'),
                title:'猫眼电影',
                subTitle:'低至8.5折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend13.png'),
                title:'淘票票代金券',
                subTitle:'低至4折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend14.png'),
                title:'话费充值',
                subTitle:'优惠快捷',
            },
        ],
        hotRecommend5:[
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend2.png'),
                title:'爱奇艺会员',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend4.png'),
                title:'优酷会员',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend5.png'),
                title:'肯德基',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend6.png'),
                title:'芒果TV',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend7.png'),
                title:'星巴克',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend8.png'),
                title:'国际驾照',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend10.png'),
                title:'饿了么会员',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend11.png'),
                title:'猫眼电影',
                subTitle:'低至8.5折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend13.png'),
                title:'淘票票代金券',
                subTitle:'低至4折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend14.png'),
                title:'话费充值',
                subTitle:'优惠快捷',
            },
        ],
        hotRecommend6:[
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend2.png'),
                title:'爱奇艺会员',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend3.png'),
                title:'美团外卖',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend5.png'),
                title:'肯德基',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend6.png'),
                title:'芒果TV',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend7.png'),
                title:'星巴克',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend8.png'),
                title:'国际驾照',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend9.png'),
                title:'大众点评',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/hotRecommend/hotRecommend14.png'),
                title:'话费充值',
                subTitle:'优惠快捷',
            },
        ],
        liveServer:[
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer1.png'),
                title:'家政服务',
                subTitle:'免费领50元券',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer2.png'),
                title:'父母体检',
                subTitle:'0元预约',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer3.png'),
                title:'腾讯王卡',
                subTitle:'免费申请',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer4.png'),
                title:'哔哩哔哩卡',
                subTitle:'免费申请',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer5.png'),
                title:'拼多多',
                subTitle:'专享购物返利',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer6.png'),
                title:'京东',
                subTitle:'专享购物返利',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer7.png'),
                title:'小米米粉卡',
                subTitle:'领特惠流量',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer8.png'),
                title:'樊登VIP福利',
                subTitle:'免费领读书卡',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer9.png'),
                title:'新人红包',
                subTitle:'美团外卖',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer10.png'),
                title:'千图网',
                subTitle:'领VIP会员',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer11.png'),
                title:'魔力耳朵英语',
                subTitle:'免费试听',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer12.png'),
                title:'汪正儿童摄影',
                subTitle:'领专属台历',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer13.png'),
                title:'盘子女人坊',
                subTitle:'定制拍摄券',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer14.png'),
                title:'话费福利',
                subTitle:'领10元话费',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer15.png'),
                title:'1元购',
                subTitle:'1元包邮到家',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer16.png'),
                title:'0元购',
                subTitle:'好货0元购',
            },
        ],
        liveServer2:[
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer1.png'),
                title:'家政服务',
                subTitle:'免费领50元券',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer2.png'),
                title:'父母体检',
                subTitle:'0元预约',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer4.png'),
                title:'哔哩哔哩卡',
                subTitle:'免费申请',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer7.png'),
                title:'小米米粉卡',
                subTitle:'领特惠流量',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer8.png'),
                title:'樊登VIP福利',
                subTitle:'免费领读书卡',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer10.png'),
                title:'千图网',
                subTitle:'领VIP会员',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer11.png'),
                title:'魔力耳朵英语',
                subTitle:'免费试听',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer12.png'),
                title:'汪正儿童摄影',
                subTitle:'领专属台历',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer13.png'),
                title:'盘子女人坊',
                subTitle:'定制拍摄券',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer14.png'),
                title:'话费福利',
                subTitle:'领10元话费',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer15.png'),
                title:'1元购',
                subTitle:'1元包邮到家',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer16.png'),
                title:'0元购',
                subTitle:'好货0元购',
            },
        ],
        liveServer5:[
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer1.png'),
                title:'家政服务',
                subTitle:'免费领50元券',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer2.png'),
                title:'父母体检',
                subTitle:'0元预约',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer4.png'),
                title:'哔哩哔哩卡',
                subTitle:'免费申请',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer7.png'),
                title:'小米米粉卡',
                subTitle:'领特惠流量',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer8.png'),
                title:'樊登VIP福利',
                subTitle:'免费领读书卡',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer10.png'),
                title:'千图网',
                subTitle:'领VIP会员',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer11.png'),
                title:'魔力耳朵英语',
                subTitle:'免费试听',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer12.png'),
                title:'汪正儿童摄影',
                subTitle:'领专属台历',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer13.png'),
                title:'盘子女人坊',
                subTitle:'定制拍摄券',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer14.png'),
                title:'话费福利',
                subTitle:'领10元话费',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer15.png'),
                title:'1元购',
                subTitle:'1元包邮到家',
            },
            {
                logo:require('@/assets/images/home/vip/liveServer/liveServer16.png'),
                title:'0元购',
                subTitle:'好货0元购',
            },
        ],
        foodDrink:[
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink1.png'),
                title:'星巴克',
                subTitle:'饮品8折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink2.png'),
                title:'麦当劳',
                subTitle:'用餐6.8折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink3.png'),
                title:'肯德基',
                subTitle:'用餐5折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink4.png'),
                title:'美团外卖',
                subTitle:'消费8折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink5.png'),
                title:'面包新语',
                subTitle:'甜品8折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink6.png'),
                title:'瑞幸咖啡',
                subTitle:'低至7.5折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink7.png'),
                title:'奈雪の茶',
                subTitle:'饮品9折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink8.png'),
                title:'必胜客',
                subTitle:'用餐9折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink9.png'),
                title:'DQ冰淇淋',
                subTitle:'低质8折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink10.png'),
                title:'真功夫',
                subTitle:'低至4折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink11.png'),
                title:'满记甜品',
                subTitle:'消费7折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink12.png'),
                title:'美团',
                subTitle:'低至8折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink13.png'),
                title:'coco都可',
                subTitle:'饮品8折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink14.png'),
                title:'汉堡王',
                subTitle:'用餐6折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink15.png'),
                title:'幸福西饼',
                subTitle:'幸福西饼',
            },
        ],
        foodDrink2:[
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink1.png'),
                title:'星巴克',
                subTitle:'饮品8折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink2.png'),
                title:'麦当劳',
                subTitle:'用餐6.8折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink3.png'),
                title:'肯德基',
                subTitle:'用餐5折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink5.png'),
                title:'面包新语',
                subTitle:'甜品8折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink6.png'),
                title:'瑞幸咖啡',
                subTitle:'低至7.5折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink7.png'),
                title:'奈雪の茶',
                subTitle:'饮品9折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink8.png'),
                title:'必胜客',
                subTitle:'用餐9折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink9.png'),
                title:'DQ冰淇淋',
                subTitle:'低质8折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink10.png'),
                title:'真功夫',
                subTitle:'低至4折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink11.png'),
                title:'满记甜品',
                subTitle:'消费7折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink13.png'),
                title:'coco都可',
                subTitle:'饮品8折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink14.png'),
                title:'汉堡王',
                subTitle:'用餐6折',
            },
            {
                logo:require('@/assets/images/home/vip/foodDrink/foodDrink15.png'),
                title:'幸福西饼',
                subTitle:'幸福西饼',
            },
        ],
        travelTrip:[
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip1.png'),
                title:'国际驾照',
                subTitle:'免费办理',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip2.png'),
                title:'加油券免领',
                subTitle:'20元加油充值券',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip3.png'),
                title:'如程酒店',
                subTitle:'每天低至1.88元',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip4.png'),
                title:'首汽约车',
                subTitle:'出行9折',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip5.png'),
                title:'惠租车',
                subTitle:'海外租车享特惠',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip6.png'),
                title:'神州专车',
                subTitle:'充值9折',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip7.png'),
                title:'曹操出行',
                subTitle:'出行9折',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip8.png'),
                title:'OYO酒店',
                subTitle:'免费领取',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip9.png'),
                title:'摩拜骑行券',
                subTitle:'低至8折',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip10.png'),
                title:'携程',
                subTitle:'携程礼品卡',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip11.png'),
                title:'橙牛洗车',
                subTitle:'免费洗车',
            },
        ],
        travelTrip2:[
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip1.png'),
                title:'国际驾照',
                subTitle:'免费办理',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip3.png'),
                title:'如程酒店',
                subTitle:'每天低至1.88元',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip8.png'),
                title:'OYO酒店',
                subTitle:'免费领取',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip10.png'),
                title:'携程',
                subTitle:'携程礼品卡',
            },
            {
                logo:require('@/assets/images/home/vip/travelTrip/travelTrip11.png'),
                title:'橙牛洗车',
                subTitle:'免费洗车',
            },
        ],
        entertainment:[
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment1.png'),
                title:'腾讯会员',
                subTitle:'充值6折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment2.png'),
                title:'爱奇艺会员',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment3.png'),
                title:'优酷会员',
                subTitle:'充值5折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment4.png'),
                title:'网易云音乐',
                subTitle:'充值5折起',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment5.png'),
                title:'芒果TV',
                subTitle:'充值5折起',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment6.png'),
                title:'酷狗音乐',
                subTitle:'低至9折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment7.png'),
                title:'酷我音乐',
                subTitle:'低至9折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment8.png'),
                title:'迅雷',
                subTitle:'低至9折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment9.png'),
                title:'懒人听书',
                subTitle:'低至8折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment10.png'),
                title:'喜马拉雅',
                subTitle:'低至7折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment11.png'),
                title:'猫眼电影',
                subTitle:'低至8.5折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment12.png'),
                title:'腾讯微云',
                subTitle:'直充9折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment13.png'),
                title:'QQ会员',
                subTitle:'直充9折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment14.png'),
                title:'QQ黄钻',
                subTitle:'直充9折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment15.png'),
                title:'咪咕影院卡',
                subTitle:'低至9折起',
            },
        ],
        entertainment2:[
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment2.png'),
                title:'爱奇艺会员',
                subTitle:'充值7折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment3.png'),
                title:'优酷会员',
                subTitle:'充值5折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment4.png'),
                title:'网易云音乐',
                subTitle:'充值5折起',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment5.png'),
                title:'芒果TV',
                subTitle:'充值5折起',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment6.png'),
                title:'酷狗音乐',
                subTitle:'低至9折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment7.png'),
                title:'酷我音乐',
                subTitle:'低至9折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment8.png'),
                title:'迅雷',
                subTitle:'低至9折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment9.png'),
                title:'懒人听书',
                subTitle:'低至8折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment10.png'),
                title:'喜马拉雅',
                subTitle:'低至7折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment11.png'),
                title:'猫眼电影',
                subTitle:'低至8.5折',
            },
            {
                logo:require('@/assets/images/home/vip/entertainment/entertainment15.png'),
                title:'咪咕影院卡',
                subTitle:'低至9折起',
            },
        ],
    },
    brand:[
        {
            logo:require('@/assets/images/home/brand1.png'),
            title:'耐克最低<b class="discountColor">3</b>折',
        },
        {
            logo:require('@/assets/images/home/brand2.png'),
            title:'阿迪最低<b class="discountColor">2</b>折',
        },
        {
            logo:require('@/assets/images/home/brand3.png'),
            title:'SKⅡ最低<b class="discountColor">4</b>折',
        },
        {
            logo:require('@/assets/images/home/brand4.png'),
            title:'香奈儿最低<b class="discountColor">3</b>折',
        },
        {
            logo:require('@/assets/images/home/brand5.png'),
            title:'古驰最低<b class="discountColor">3</b>折',
        },
        {
            logo:require('@/assets/images/home/brand6.png'),
            title:'祖玛珑最低<b class="discountColor">4</b>折',
        },
        {
            logo:require('@/assets/images/home/brand7.png'),
            title:'迪奥最低<b class="discountColor">3</b>折',
        },
        {
            logo:require('@/assets/images/home/brand8.png'),
            title:'阿玛尼最低<b class="discountColor">3</b>折',
        },
    ],
    rights:[
        {
            logo:require('@/assets/images/home/rights1.png'),
            title:'口腔健康',
            subTitle:'最高立减 300元',
        },
        {
            logo:require('@/assets/images/home/rights2.png'),
            title:'体检权益',
            subTitle:'体检立减 300元',
        },
        {
            logo:require('@/assets/images/home/rights3.png'),
            title:'酒店礼包',
            subTitle:'覆盖全国25 万家酒店',
        },
        {
            logo:require('@/assets/images/home/rights4.png'),
            title:'机票立减',
            subTitle:'12次累计可 领50元券',
        },
        {
            logo:require('@/assets/images/home/rights5.png'),
            title:'景点门票',
            subTitle:'12次约省 30元',
        },
        {
            logo:require('@/assets/images/home/rights6.png'),
            title:'周边游立减',
            subTitle:'4次最高减 150元',
        },
        {
            logo:require('@/assets/images/home/rights7.png'),
            title:'火车票立减',
            subTitle:'12次累计可 领20元券',
        },
    ],
};

export default{
    datas
}