const datas = {
    privilege:[
        {
            logo:require('@/assets/images/home/privilege1.png'),
            title:'0元购',
            subTitle:'1000+好货',
            label:false,
        },
        {
            logo:require('@/assets/images/home/privilege2.png'),
            title:'新人红包',
            subTitle:'最高可送50元!',
            label:false,
        },
        {
            logo:require('@/assets/images/home/privilege3.png'),
            title:'购物返利',
            subTitle:'购物还可拿钱!',
            label:false,
        },
        {
            logo:require('@/assets/images/home/privilege4.png'),
            title:'加油优惠',
            subTitle:'9折起优惠',
            label:true,
        },
        {
            logo:require('@/assets/images/home/privilege5.png'),
            title:'全球大牌',
            subTitle:'精选顶级奢侈品',
            label:false,
        },
        {
            logo:require('@/assets/images/home/privilege6.png'),
            title:'吃喝玩乐',
            subTitle:'星巴克永久折',
            label:false,
        },
    ],
    discount:[
        {
            logo:require('@/assets/images/home/discount5.png'),
            title:'话费立减券',
            subTitle:'移动电信联通',
            label:true,
        },
        {
            logo:require('@/assets/images/home/discount1.png'),
            title:'优酷会员',
            subTitle:'会员4折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount2.png'),
            title:'爱奇艺会员',
            subTitle:'会员5折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount3.png'),
            title:'腾讯会员',
            subTitle:'会员5折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount4.png'),
            title:'QQ音乐会员',
            subTitle:'会员4折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount7.png'),
            title:'网易云会员',
            subTitle:'会员低折扣',
            label:false,
        },
        {
            logo:require('@/assets/images/home/discount8.png'),
            title:'喜马拉雅',
            subTitle:'会员立减券',
            label:false,
        },
    ],
    eatDiscount:[
        {
            logo:require('@/assets/images/home/eatDiscount1.png'),
            title:'肯德基',
            subTitle:'会员6折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/eatDiscount2.png'),
            title:'必胜客',
            subTitle:'尊享5折起',
            label:true,
        },
        {
            logo:require('@/assets/images/home/eatDiscount3.png'),
            title:'周黑鸭',
            subTitle:'特惠5折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/eatDiscount4.png'),
            title:'外卖立减',
            subTitle:'红包天天领',
            label:false,
        },
        {
            logo:require('@/assets/images/home/eatDiscount5.png'),
            title:'星巴克咖啡',
            subTitle:'会员立减券',
            label:true,
        },
        {
            logo:require('@/assets/images/home/eatDiscount6.png'),
            title:'瑞幸咖啡',
            subTitle:'会员立减券',
            label:true,
        },
        {
            logo:require('@/assets/images/home/eatDiscount7.png'),
            title:'Costa咖啡',
            subTitle:'特惠5折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/eatDiscount8.png'),
            title:'太平洋咖啡',
            subTitle:'特惠7折起',
            label:false,
        },
        {
            logo:require('@/assets/images/home/eatDiscount9.png'),
            title:'8折看电影',
            subTitle:'会员季卡9.9元',
            label:true,
        },
        {
            logo:require('@/assets/images/home/eatDiscount10.png'),
            title:'生鲜水果',
            subTitle:'9.9元秒杀优惠',
            label:false,
        },
        {
            logo:require('@/assets/images/home/eatDiscount11.png'),
            title:'零食优惠',
            subTitle:'9.9元秒杀优惠',
            label:false,
        },
        {
            logo:require('@/assets/images/home/eatDiscount12.png'),
            title:'玩具折扣',
            subTitle:'9.9元秒杀优惠',
            label:false,
        },
    ],
    brand:[
        {
            logo:require('@/assets/images/home/brand1.png'),
            title:'耐克最低<b class="discountColor">3</b>折',
        },
        {
            logo:require('@/assets/images/home/brand2.png'),
            title:'阿迪最低<b class="discountColor">2</b>折',
        },
        {
            logo:require('@/assets/images/home/brand3.png'),
            title:'SKⅡ最低<b class="discountColor">4</b>折',
        },
        {
            logo:require('@/assets/images/home/brand4.png'),
            title:'香奈儿最低<b class="discountColor">3</b>折',
        },
        {
            logo:require('@/assets/images/home/brand5.png'),
            title:'古驰最低<b class="discountColor">3</b>折',
        },
        {
            logo:require('@/assets/images/home/brand6.png'),
            title:'祖玛珑最低<b class="discountColor">4</b>折',
        },
        {
            logo:require('@/assets/images/home/brand7.png'),
            title:'迪奥最低<b class="discountColor">3</b>折',
        },
        {
            logo:require('@/assets/images/home/brand8.png'),
            title:'阿玛尼最低<b class="discountColor">3</b>折',
        },
    ],
    rights:[
        {
            logo:require('@/assets/images/home/rights1.png'),
            title:'口腔健康',
            subTitle:'最高立减 300元',
        },
        {
            logo:require('@/assets/images/home/rights2.png'),
            title:'体检权益',
            subTitle:'体检立减 300元',
        },
        {
            logo:require('@/assets/images/home/rights3.png'),
            title:'酒店礼包',
            subTitle:'覆盖全国25 万家酒店',
        },
        {
            logo:require('@/assets/images/home/rights4.png'),
            title:'机票立减',
            subTitle:'12次累计可 领50元券',
        },
        {
            logo:require('@/assets/images/home/rights5.png'),
            title:'景点门票',
            subTitle:'12次约省 30元',
        },
        {
            logo:require('@/assets/images/home/rights6.png'),
            title:'周边游立减',
            subTitle:'4次最高减 150元',
        },
        {
            logo:require('@/assets/images/home/rights7.png'),
            title:'火车票立减',
            subTitle:'12次累计可 领20元券',
        },
    ],
};

export default{
    datas
}